name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++

      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: cmake --build build

      - name: Run executable
        run: ./build/app
